name: Export Crunched Textures

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-2022.3.22f1-base-3.1.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Unity Editor
        uses: unity-ci/editor@v3
        with:
          version: 2022.3.22f1

      - name: Activate Unity License
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        run: |
          unity -batchmode -nographics -quit -logFile \
          -username "$UNITY_EMAIL" -password "$UNITY_PASSWORD"

      - name: Export Crunched Textures
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
          unity-editor \
            -batchmode \
            -projectPath . \
            -executeMethod ExportCrunchedBytes.Export \
            -logFile - \
            -quit

      - name: Upload Unity log if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: unity-editor-log
          path: /root/.config/unity3d/Editor.log

      - name: Upload exported bytes
        uses: actions/upload-artifact@v4
        with:
          name: crunched-bytes
          path: Assets/Output/
