name: Export Crunched Textures

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-2022.3.22f1-base-3.1.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Unity license
        run: |
          mkdir -p ~/.local/share/unity3d
          echo "${{ secrets.UNITY_LICENSE }}" > ~/.local/share/unity3d/Unity_v2019.x.ulf

      - name: Set up Unity
        uses: unity-actions/setup@v2
        with:
          unityVersion: 2022.3.22f1

      - name: Export Crunched Textures
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
          unity-editor \
            -batchmode \
            -projectPath . \
            -executeMethod ExportCrunchedBytes.Export \
            -logFile - \
            -quit

      - name: Upload Unity log if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: unity-editor-log
          path: /root/.config/unity3d/Editor.log

      - name: Upload exported bytes
        uses: actions/upload-artifact@v4
        with:
          name: crunched-bytes
          path: Assets/Output/
