name: Export Crunched Textures

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-2022.3.22f1-base-3.1.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Activate Unity
        uses: game-ci/unity-activate@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      #- name: Set up Unity license
      #  run: |
      #    mkdir -p ~/.local/share/unity3d
      #    echo "${{ secrets.UNITY_LICENSE }}" > ~/.local/share/unity3d/Unity_lic.ulf
      #    echo "${{ secrets.UNITY_LICENSE }}" > ~/.local/share/unity3d/Unity_v2022.x.ulf

      - name: Export Crunched Textures
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
          unity \
            -batchmode \
            -projectPath . \
            -executeMethod ExportCrunchedBytes.Export \
            -logFile - \
            -quit

#-username ${{ secrets.UNITY_EMAIL }} \
#-password ${{ secrets.UNITY_PASSWORD }} \

      # Unityプロジェクトのビルド
      # 設定しない場合、buildフォルダに出力される
      #- name: Run the Windows build
      #  uses: game-ci/unity-builder@v4
      #  env:
      #    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #  with:
      #    targetPlatform: StandaloneWindows64
      #    unityVersion: 2022.3.22f1

      - name: Upload Unity log if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: unity-editor-log
          path: /root/.config/unity3d/Editor.log

      - name: Upload exported bytes
        uses: actions/upload-artifact@v4
        with:
          name: crunched-bytes
          path: Assets/Output/
